export const GAME_CONFIG = {
  economy: {
    naturalSunInterval: 7,
    sunValue: 25,
  },
  plants: {
    moonbud: {
      cost: 50,
      cooldown: 7.5,
      hp: 300,
      sunInterval: 14,
    },
    thornsnap: {
      cost: 100,
      cooldown: 7.5,
      hp: 300,
      damage: 20,
      attackInterval: 1.4,
      seedSpeed: 300,
    },
    barkbulwark: {
      cost: 50,
      cooldown: 30,
      hp: 4000,
    },
    frostlily: {
      cost: 175,
      cooldown: 7.5,
      hp: 300,
      damage: 20,
      attackInterval: 1.4,
      seedSpeed: 300,
      slowFactor: 0.5,
      slowDuration: 1.5,
    },
    twinfang: {
      cost: 200,
      cooldown: 7.5,
      hp: 300,
      damage: 20,
      attackInterval: 1.4,
      seedSpeed: 300,
      secondShotDelay: 0.15,
    },
    blastcap: {
      cost: 150,
      cooldown: 45,
      hp: 300,
      damage: 1800,
      radiusCells: 1,
      fuseDuration: 0.4,
    },
    emberroot: {
      cost: 25,
      cooldown: 7.5,
      hp: 500,
    },
    dreamspore: {
      cost: 75,
      cooldown: 7.5,
      hp: 400,
    },
    glacierbloom: {
      cost: 100,
      cooldown: 7.5,
      hp: 3000,
      damage: 35,
      attackInterval: 1.4,
      seedSpeed: 300,
      slowFactor: 0.5,
      slowDuration: 1.5,
    },
  },
  zombies: {
    husk: {
      hp: 200,
      speed: 15,
      attackPower: 100,
    },
    podhead: {
      hp: 200,
      armorHp: 370,
      speed: 15,
      attackPower: 100,
    },
    stumphusk: {
      hp: 200,
      armorHp: 1100,
      speed: 15,
      attackPower: 100,
    },
  },
  combat: {
    zombieAttackInterval: 1,
  },
} as const;
