export const GAME_CONFIG = {
  economy: {
    naturalSunInterval: 7,
    sunValue: 25,
  },
  plants: {
    sunflower: {
      cost: 50,
      cooldown: 7.5,
      hp: 300,
      sunInterval: 14,
    },
    peashooter: {
      cost: 100,
      cooldown: 7.5,
      hp: 300,
      damage: 20,
      attackInterval: 1.4,
      peaSpeed: 300,
    },
    wallnut: {
      cost: 50,
      cooldown: 30,
      hp: 4000,
    },
    snowpea: {
      cost: 175,
      cooldown: 7.5,
      hp: 300,
      damage: 20,
      attackInterval: 1.4,
      peaSpeed: 300,
      slowFactor: 0.5,
      slowDuration: 1.5,
    },
    repeater: {
      cost: 200,
      cooldown: 7.5,
      hp: 300,
      damage: 20,
      attackInterval: 1.4,
      peaSpeed: 300,
      secondShotDelay: 0.15,
    },
    cherrybomb: {
      cost: 150,
      cooldown: 45,
      hp: 300,
      damage: 1800,
      radiusCells: 1,
      fuseDuration: 0.4,
    },
    torchwood: {
      cost: 25,
      cooldown: 7.5,
      hp: 500,
    },
    hypnoshroom: {
      cost: 75,
      cooldown: 7.5,
      hp: 400,
    },
    iceshroom: {
      cost: 100,
      cooldown: 7.5,
      hp: 3000,
      damage: 35,
      attackInterval: 1.4,
      peaSpeed: 300,
      slowFactor: 0.5,
      slowDuration: 1.5,
    },
  },
  zombies: {
    basic: {
      hp: 200,
      speed: 15,
      attackPower: 100,
    },
    conehead: {
      hp: 200,
      armorHp: 370,
      speed: 15,
      attackPower: 100,
    },
    buckethead: {
      hp: 200,
      armorHp: 1100,
      speed: 15,
      attackPower: 100,
    },
  },
  combat: {
    zombieAttackInterval: 1,
  },
} as const;
